select
    cast(movie_id as int64) as movie_id,
    cast(snapshot_date as date) as snapshot_date,
    title,
    original_title,
    original_language,
    overview,
    homepage,
    imdb_id,
    cast(release_date as date) as release_date,
    cast(runtime as int64) as runtime,
    status,
    tagline,
    cast(adult as bool) as adult,
    cast(video as bool) as video,
    cast(budget as int64) as budget,
    cast(revenue as int64) as revenue,
    cast(popularity as float64) as popularity,
    cast(vote_average as float64) as vote_average,
    cast(vote_count as int64) as vote_count,
    poster_path,
    backdrop_path,
    source_file
from {{ source('tmdb_silver', 'movies') }}